[package]
name = "fetcher"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
thiserror = { workspace = true }
flate2 = "1"
tar = "0.4"
ureq = { version = "2", default-features = false, features = ["tls"] }

[dev-dependencies]
tempfile = "3"
